### ISSUE TITLE
Create full project in Drupal.org

### ISSUE THREAD

**Issue by e0ipso** [briancwald/dfs-admin#1]
Can you please promote https://www.drupal.org/sandbox/brian14/2834539 to a full project. Now everyone can create full projects, so you have access to do that.

I want to use this fantastic theme in a community driven API-First distribution. I love the material integration and that it's mobile first. Having a full project in drupal.org will allow me to install the module using composer.

Thanks!

**Comment by briancwald** [comment]
Hey there, glad you like it! the reason I haven't promoted it yet is because there are some unusable areas of the theme, such as views admin. I can promote it, though you will definitely run into some big issues. I plan to work on those things in the very near future though, so I am still actively developing, I just didn't have time for the past month to get back to it. I am more than willing to accept any pull requests or help! Take a look at my github page for updates on what needs to be done.

________________________________

**Comment by e0ipso** [comment]
I see! Thanks for sharing. Please let me know in this issue when those wrinkles have been ironed. 

We'll go with a different theme for the time being, but I want to switch to this one as soon as possible!

**Comment by briancwald** [comment]
Ill keep the readme up to date.

**Comment by briancwald** [comment]
FWIW, I did push it as a full project and added a disclaimer to the top. I will keep you updated on feature completeness but I am going to close this ticket.

**Comment by e0ipso** [comment]
Can you also create the `8.x-1.x-dev` release please?

**Comment by briancwald** [comment]
Done

**Comment by e0ipso** [comment]
🎉

**Comment by e0ipso** [comment]
Keep those improvements coming. We hope to give this them quite some visibility!

https://github.com/drupal-http-apis/contenta_jsonapi/blob/master/composer.json#L53
