### ISSUE TITLE
Textarea is too small when there is a text format

### ISSUE THREAD

**Issue by e0ipso** [briancwald/dfs-admin#6]
The resizable textarea is too small. This happens when there is a textformat companion item.

![edit recipe kibbeh contenta json api 2017-05-21 00-13-35](https://cloud.githubusercontent.com/assets/1140906/26279679/87493f78-3dba-11e7-9a8e-8c7dcef40bc8.png)

**Comment by e0ipso** [comment]
It happens without a text format as well.

![add media bundle contenta json api 2017-05-21 07-51-49](https://cloud.githubusercontent.com/assets/1140906/26281543/6b559312-3dfa-11e7-9158-b78b1ef56b11.png)

**Comment by briancwald** [comment]
Yeah. I have a ticket out for materializecss framework about text areas because their formatting does not conform to google's documentation. https://material.io/guidelines/components/text-fields.html#text-fields-field-types

I think I will just create my own styles for this based on google docs because that issue has been open for 4+ months.

**Comment by briancwald** [comment]
fixed basic to use col defaults and proper outline styling with transition
![texarea-empty](https://cloud.githubusercontent.com/assets/776942/26284547/f95469c0-3e0b-11e7-8e7d-aac9625de7ce.gif)
